#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global _$name\n";
    print "_${name}:\n";
    print " csrr t3, modeid\n";
    print " slli t3, t3, 47\n";
    print " li a7, SYS_${name}\n";
    print " or a7, a7, t3\n";
    print " csrw ccalladdr, a7\n";
    print " pcall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("reboot");
entry("rdtime");
entry("mcreate");
entry("mdelete");
entry("mentry");
entry("lseek");
entry("permchange");
entry("access");
